import { defaultSchema, type Schema } from 'hast-util-sanitize';
import React from 'react';
import type { Components } from 'react-markdown';
import ReactMarkdown from 'react-markdown';
import rehypeHighlight from 'rehype-highlight';
import rehypeSanitize from 'rehype-sanitize';
import remarkGfm from 'remark-gfm';

import { cn } from '@/lib/utils';

const sanitizeSchema: Schema = {
  ...defaultSchema,
  attributes: {
    ...defaultSchema.attributes,
    code: [...(defaultSchema.attributes?.code || []), ['className']],
    pre: [...(defaultSchema.attributes?.pre || []), ['className']],
    span: [...(defaultSchema.attributes?.span || []), ['className']],
  },
};

const components = {
  a: ({ children, href, ...props }: any) => (
    <a
      href={href}
      target="_blank"
      rel="noreferrer noopener"
      className="underline underline-offset-2"
      {...props}
    >
      {children}
    </a>
  ),
  pre: ({ children, className, ...props }: any) => (
    <pre
      className={cn(
        'rounded-md bg-muted/60 p-3 text-xs leading-relaxed font-mono whitespace-pre-wrap',
        className,
      )}
      {...props}
    >
      {children}
    </pre>
  ),
  code: ({ children, className, ...props }: any) => {
    const { inline, ...rest } = props;
    const isInline = inline === true;
    const codeClass = isInline
      ? cn('font-mono rounded bg-muted/60 px-1 py-0.5 text-[0.85em]', className)
      : cn('font-mono whitespace-pre-wrap break-words', className);

    return (
      <code className={codeClass} {...rest}>
        {children}
      </code>
    );
  },
  ul: ({ children, ...props }: any) => (
    <ul className="list-disc pl-5" {...props}>
      {children}
    </ul>
  ),
  ol: ({ children, ...props }: any) => (
    <ol className="list-decimal pl-5" {...props}>
      {children}
    </ol>
  ),
  li: ({ children, ...props }: any) => (
    <li className="my-1" {...props}>
      {children}
    </li>
  ),
  p: ({ children, ...props }: any) => (
    <p className="my-2" {...props}>
      {children}
    </p>
  ),
  // headings generated by factory below
} satisfies Components;

function headingFactory(level: number) {
  // formulaic scale: base (h1) and ratio (multiply previous by ratio for next)
  const base = 1.4; // rem for h1
  const ratio = 0.85; // multiply previous size by this to get next
  const sizes = Array.from({ length: 6 }, (_, i) => Number((base * Math.pow(ratio, i)).toFixed(4)));
  const mbs = ['my-[2.2]', 'my-[1.8]', 'my-[1.4]', 'my-[1.2]', 'my-[1]', 'my-[1]'];
  return ({ children, className, style, ...props }: any) => {
    const weight = level === 1 ? 'font-bold' : 'font-semibold';
    const classStr = cn('scroll-m-20', weight, mbs[level - 1], className);
    const Tag = `h${level}`;
    const fontSize = sizes[level - 1];
    const mergedStyle = { ...(style || {}), fontSize: `${fontSize}rem` } as React.CSSProperties;
    return React.createElement(
      Tag,
      { className: classStr, style: mergedStyle, ...props },
      children,
    );
  };
}

// Attach generated heading renderers (h1..h6)
for (let i = 1; i <= 6; i++) {
  // @ts-ignore assign into components object
  (components as any)[`h${i}`] = headingFactory(i);
}

export function SafeMarkdown({ content }: { content?: string }) {
  if (!content) return null;

  return (
    <ReactMarkdown
      remarkPlugins={[remarkGfm]}
      rehypePlugins={[rehypeHighlight as any, [rehypeSanitize, sanitizeSchema]]}
      components={components}
    >
      {content}
    </ReactMarkdown>
  );
}
